### ISSUE TITLE
以 Meetup 為例

### ISSUE THREAD

**Issue by wjmuse** [HadoopTW/communities-dashboard#1]
在UK有人透過meetup api做過`skill set network`
- http://www.nesta.org.uk/blog/using-meetup-data-explore-uk-digital-tech-landscape

也有熱心民眾提供了R的source code
- http://trendct.org/2015/04/03/using-python-and-r-to-pull-and-analyze-meetup-com-api-data/

不嫌棄的話，小弟想透過這塊做些練習 :)

**Comment by jazzwang** [comment]
Cool~ 已邀請您加入 Community-Dashboard 專案~

**Comment by jazzwang** [comment]
將相關連結加入 Wiki
https://github.com/HadoopTW/communities-dashboard/wiki/Data-Source-API-Notes
